module "general" {
  source                 = "./modules/general"
  profile            = local.profile
  ambiente            = var.ambiente
  projeto                = local.projeto
  criado_por              = local.criado_por
  public-subnet_ids      = var.vpc_publicSubNetIds
  private-subnet_ids     = var.vpc_privateSubNetIds
  avaiable_zones         = var.vpc_avaiable_zones
  regiao             = var.regiao
  regiao_names       = var.regiao_names
  aws_vpc_id             = var.vpc_id
  internal_ip_ssh        = var.internal_ip_ssh
  key_pair_futura        = var.key_pair_futura
  amis                   = var.amis
  instance_type          = var.instance_type
  futuraBucketName       = var.futuraBucketName
  sns-emails             = var.sns-emails
  account_id             = local.account_id
  prefix-list-id         = var.prefix-list-id
  sg-ecs-service_id      = var.sg-ecs-service-id
  root-block-device-size = var.root-block-device-size
  sg-lambda-id           = var.sg-lambda-id
  sg-teste-carga-id      = var.sg-teste-carga-id
  sg-rds-id              = var.sg-rds-id
  sg-observabilidade-id  = var.sg-observabilidade-id
  rds_endpoint           = var.rds_endpoint
}