variable "ambiente" {}
variable "projeto" {}
variable "regiao" {}
variable "autoscale-min" {}
variable "autoscale-max" {}
variable "aws-vpc-id" {}
variable "public-subnet-ids" {}
variable "account-id" {}
variable "today" {}
variable "sg-lb-id" {}
variable "sg-ecs-service-id" {}
variable "ecstagresourcepolicyarn" {}
variable "aws-ecr-repository-name" {}