extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    # logLevel: debug
  file/traces:
    path: /log/otel/traces.log
  file/metrics:
    path: /log/otel/metrics.log
  file/logs:
    path: /log/otel/logs.log
  otlp:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "${PROMETHEUS_ENDPOINT}"

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - logging 
        - file/traces
        - otlp
    metrics:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - logging 
        - file/metrics
        - prometheus
  extensions:
    - health_check
    - zpages
